docs: add ip-restriction plugin document
api7/docs.apiseven.com pull request #12
Opened 2023-04-26 07:02 UTC by mscb402

2023-04-27 03:29 UTC, sijingzhangzsj0604 requested changes

2023-04-27 03:29 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +  "whitelist": ["你的本地外网IP"],
直接给出一个具体的IP地址作为示例放在代码中，用注释方式说明用你的本地外网IP。保证所有的代码复制即可用

2023-04-27 03:29 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +curl -X POST -d "{xxx}" -v http://${BASE_URL}/products
给出具体的base_url，保证所有代码复制即可访问。这个base_url如果跨多篇文章共享则需要统一。

2023-04-27 03:29 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +curl -x http://proxy-server:port -d "{xxx}" -X POST http://${BASE_URL}/products
给出具体地址

2023-04-27 05:32 UTC, mscb402 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +  "whitelist": ["你的本地外网IP"],
改了

2023-04-27 05:33 UTC, mscb402 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +curl -X POST -d "{xxx}" -v http://${BASE_URL}/products
改为test.com了

2023-04-27 05:33 UTC, mscb402 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +curl -x http://proxy-server:port -d "{xxx}" -X POST http://${BASE_URL}/products
改了

2023-04-27 06:04 UTC, moonming requested changes

2023-04-27 06:04 UTC, moonming commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +在当今数字化时代，API 已成为珍贵的资产。它的作用跨越了许多领域，但这也使其成为网络攻击的目标。为了保护某些敏感 API 的安全，阻止特定 IP 地址访问 API 和使用 IP 白名单成为了延长 API 生命周期的最佳实践之一。
这是文档，不是文章，不需要这些铺垫

2023-04-27 06:04 UTC, moonming commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +为了实现 ip restriction 功能，我们需要在了解 Apache APISIX 的 [ip restriction](https://apisix.apache.org/docs/apisix/plugins/ip-restriction/) 插件的配置属性。
企业版文档不要引用开源文档

2023-04-27 06:04 UTC, moonming commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +:::
不需要任何原理的讲解。
需要的是企业版的步骤

2023-04-27 06:13 UTC, moonming requested changes

2023-04-27 06:13 UTC, moonming commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +## 验证
下面步骤的验证难度太大，我觉得没人能跟着跑通

2023-04-27 06:13 UTC, moonming commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +
重新设计场景和案例，现在的没法让用户复现

2023-04-28 08:11 UTC, mscb402 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +为了实现 ip restriction 功能，我们需要在了解 Apache APISIX 的 [ip restriction](https://apisix.apache.org/docs/apisix/plugins/ip-restriction/) 插件的配置属性。
去掉了

2023-04-28 08:12 UTC, mscb402 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +:::
已经按照你的要求，把这一段讲解去掉了

2023-04-28 08:12 UTC, mscb402 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/handling-ip-restriction.md
> +## 验证
换了一种验证方式

2023-05-16 15:37 UTC, merged