docs: optimize the design-apis.md
api7/docs.apiseven.com pull request #13
Opened 2023-04-28 03:01 UTC by tokers

2023-05-15 12:37 UTC, sijingzhangzsj0604 requested changes

2023-05-15 12:37 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/design-apis.md
> +![Create Order](https://static.apiseven.com/uploads/2023/04/28/Kcxszff1_CreateOrder.png)
这个图片好像和create product重复了

2023-05-16 01:48 UTC, Baoyuantop commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/design-apis.md
>  接下来，我们在 Postman 上创建一个名为 `shop` 的 Collection，然后在该 Collection 下依次创建三个 API，分别是 `GetProductById`、`CreateProduct`、`CreateOrder`。
`shop` 的 Collection 前面已经创建过了

2023-05-16 01:58 UTC, tokers commented on enterprise_versioned_docs/version-2.13.x/api-full-lifecycle/design-apis.md
>  接下来，我们在 Postman 上创建一个名为 `shop` 的 Collection，然后在该 Collection 下依次创建三个 API，分别是 `GetProductById`、`CreateProduct`、`CreateOrder`。
OK

2023-05-16 07:02 UTC, merged