feat: add doc about developer
api7/docs.apiseven.com pull request #2
Opened 2023-03-16 07:32 UTC by Hazel6869

2023-03-18 09:10 UTC, sijingzhangzsj0604 requested changes

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +1. API 的使用者，网关测的用户的用户，以组织为单位进行管理，与之对应的概念是 API 生产者，也就是网关测的用户。
API 的实际使用者，以组织为单位进行管理。与之对应的概念是 API 生产者，也就是操作API7网关并发布API的用户。开发者只能使用开发者门户，不能登录并使用API7网关。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +2. 网关测的用户想成为开发者，可以通过增加开发者的方式。
API7网关中的用户自动获得开发者身份，可以登录开发者门户并使用API。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +3. 开发者的角色分为普通开发者和管理员，MVP 版本默认都是管理员角色。
删掉这一句，不要给用户提及MVP版本。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +帮助网关测的用户和开发者本身识别并了解开发者。
识别并了解开发者。（注意错别字）

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +以组织为单位对开发者进行管理，网关侧不感知，MVP 版本只有 default 组织。组织主要包含两部分：
开发者的组织信息与网关本身无关，不会对网关产生任何影响。目前只提供默认的default组织，后续支持开发者自定义创建并管理组织。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +1. Payment：未来为创建 application、创建 route、调用 api 等功能而付费的账户，对接 [stripe](https://stripe.com/zh-cn-us)。
去掉，用户还不感知的东西都不提

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +2. Developer list：组织内所有人员，包括管理员和非管理员角色，MVP 版本都是管理员角色。
去掉

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +帮助网关测的用户和开发者本身识别并了解组织。
识别并了解组织。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +创建开发者时需要填写邮箱信息，作为开发者登陆开发者门户系统的默认账号和密码，因此在系统层面具有唯一性。
默认账号，没有密码。同一个邮箱只能创建一个开发者账号并属于唯一一个组织。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +## 编辑开发者 （MVP版本不支持）
不要提MVP版本，去掉括号

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +只可由开发者自行操作，不支持在管理端编辑。
后续将支持开发者自行操作，但不支持在管理端编辑。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +## 删除开发者 （MVP版本不支持）
不要提MVP版本，括号去掉

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +只可由开发者自行操作，不支持在管理端编辑。
后续将支持开发者自行操作，但不支持在管理端删除。

2023-03-18 09:10 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +- 使用限制：开发者的邮箱，会作为登陆开发者门户系统账户的默认账号和密码，因此在系统层面具有唯一性；需要提前创建开发者所在的组织信息。
增加一行：不支持变更开发者所在组织，只能删除开发者后重新创建。

2023-03-22 06:12 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +2. 网关测的用户想成为开发者，可以通过增加开发者的方式。
我们技术方案讨论是 API7网关中的用户 也需要通过 新增开发者的方式添加自己的账号，而不是自动成为的。

2023-03-22 06:14 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +帮助网关测的用户和开发者本身识别并了解开发者。
我没有看出哪里有错误子 😂
![image](https://user-images.githubusercontent.com/30279880/226817634-f163a635-722c-45a3-b461-451779238acd.png)

2023-03-22 06:18 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +1. API 的使用者，网关测的用户的用户，以组织为单位进行管理，与之对应的概念是 API 生产者，也就是网关测的用户。
done

2023-03-22 06:18 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +3. 开发者的角色分为普通开发者和管理员，MVP 版本默认都是管理员角色。
done

2023-03-22 06:19 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +以组织为单位对开发者进行管理，网关侧不感知，MVP 版本只有 default 组织。组织主要包含两部分：
done

2023-03-22 06:19 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +## 编辑开发者 （MVP版本不支持）
done

2023-03-22 06:19 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +只可由开发者自行操作，不支持在管理端编辑。
done

2023-03-22 06:19 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +## 删除开发者 （MVP版本不支持）
done

2023-03-22 06:23 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +只可由开发者自行操作，不支持在管理端编辑。
done

2023-03-22 06:23 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +创建开发者时需要填写邮箱信息，作为开发者登陆开发者门户系统的默认账号和密码，因此在系统层面具有唯一性。
done

2023-03-22 06:23 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +帮助网关测的用户和开发者本身识别并了解组织。
这里没有理解怎么修改

2023-03-23 01:45 UTC, Hazel6869 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +- 使用限制：开发者的邮箱，会作为登陆开发者门户系统账户的默认账号和密码，因此在系统层面具有唯一性；需要提前创建开发者所在的组织信息。
done

2023-03-28 01:58 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +2. 网关测的用户想成为开发者，可以通过增加开发者的方式。
先这样吧

2023-03-28 01:59 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +帮助网关测的用户和开发者本身识别并了解开发者。
测 -》 侧

2023-03-28 01:59 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-2.8.2206/开发者门户/开发者.md
> +帮助网关测的用户和开发者本身识别并了解组织。
不需要前面的帮助谁。而且你所有的网关侧都错别字成了测

2023-03-28 11:05 UTC, merged