[API7 EE]--Use API7 EE to proxy gRPC services
api7/docs.apiseven.com pull request #44
Opened 2024-01-31 12:27 UTC by Huanli-Meng

### Motivation

Fill in content gap by adding more use cases.

### Modification

- Create a new category: Best Practices
- Add a new doc:
- Update the `sidebar.json` file

### Preview

2024-02-01 09:41 UTC, sijingzhangzsj0604 requested changes

2024-02-01 09:41 UTC, sijingzhangzsj0604 commented on enterprise_versioned_docs/version-3.2.7.1/best-practices/configure-grpc.md
default Gateway group 中文 不需要翻译，和控制台对不上

2024-02-02 01:26 UTC, Huanli-Meng commented on enterprise_versioned_docs/version-3.2.7.1/best-practices/configure-grpc.md
是指的这个么？在中文版里，我们把网关名字改成中文了。

> 选择 `缺省网关组`，然后单击**下一步**。

2024-02-23 01:02 UTC, sijingzhangzsj0604 approved these changes

2024-02-23 01:10 UTC, merged